### PR TITLE
D2-C2 plugin

### PR DESCRIPTION
**Pull request by jbueno-nommon**
An initial version of the plugin which manages all the features of the D2-C2 method.

To start the plugin: `PLUGIN USEPE`

It includes different classes:
- usepegraph: graph representing the city.
- usepesegments: integration of the segmentation service
- usepeflightplans: flight plans processing
- usepestrategic: strategic deconfliction service
- usepedronecommands: BlueSky commands creator

This initial version is able to read a CSV with all the flights during the simulation. An example of the file is included below:

,origin_lat,origin_lon,origin_alt,destination_lat,destination_lon,destination_alt,departure,departure_s,drone,purpose,planned_time_s
0,52.362,9.735,50,52.378,9.738,50,0:01:00,60,M600,delivery,0
1,52.372,9.745,50,52.378,9.738,50,0:01:30,90,M600,background,0

The workflow is the following:

1.  t< planned_time_s: do nothing
2. t=planned_time_s: process the flight plan (i.e., compute a strategic deconflicted flight plan)
3. planned_time_s < t < departure_s + delay (if apply according to the strategic deconfliction service): if the segments are updated, the flight plan is reprocessed (rerouting or delay are available options).
4. t=departure_s + delay: BlueSky commands are created
5.  t>departure_s + delay: if the segments are updated, the drone is rerouted

I have focussed on last mile delivery use case: delivery drones and background traffic. I will need your help to understand the needs of the other use cases.

Please let me know your thoughts about this approach. Any suggestions are welcome.

### CODE REVIEW

**Review by SerkanGuldal — APPROVED** [review]

**Comment by SerkanGuldal** [comment]
Hi @jbuenoNommon,
I tried to run it but following message opoped up. Do you know why it happened?
image

**Comment by jbueno-nommon** [comment]
Hi @SerkanGuldal,
It seems you have an issue with an installation of a library and its dependencies. In case you do not know, we are using OSMnx and NetworkX to create and use graphs.
This [link](https://stackoverflow.com/questions/45901732/could-not-find-or-load-spatialindex-c-dll-in-windows) may help you.

**Comment by SerkanGuldal** [comment]
Hi @jbuenoNommon,
I already have those libraries. 
The definition you left is not enough to run.
Can you provide step step step guide with an example?

**Comment by jbueno-nommon** [comment]
> Hi @jbuenoNommon, I already have those libraries. The definition you left is not enough to run. Can you provide step step step guide with an example?

Hi @SerkanGuldal,

The steps to run the usepe plugin are:
1. Open `usepe_plugin.py` and modify the following lines in the `init_plugin()` function (to include these input parameters in a config file is a pending task, and it will be done in the next version of the plugin):
  * config_path: introduce the path to the config file. This config file is the same that you have used to create the graph.
  * graph_path: introduce the path to the graph file.
  * segment_path: introduce the path to the segment file.
  * flight_plan_csv_path: introduce the path to the csv file with information of the flights.
2. Run `BlueSky.py`
3. Optional: introduce the command `VIS MAP TILEDMAP`
4.  Introduce the command `PLUGIN USEPE`
5.  Press button **Op** in the Simulation Controls panel

**Pull request merged**
